# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  "evilz.vscode-reveal" = {
    pname = "evilz.vscode-reveal";
    version = "4.3.3";
    src = fetchurl {
      url = "https://evilz.gallery.vsassets.io/_apis/public/gallery/publisher/evilz/extension/vscode-reveal/4.3.3/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-reveal-4.3.3.zip";
      sha256 = "sha256-KqvQi0DMfHppX96qKHIkO9zIueBdGGV+6dYkpFEzFBo=";
    };
  };
  "janisdd.vscode-edit-csv" = {
    pname = "janisdd.vscode-edit-csv";
    version = "0.11.7";
    src = fetchurl {
      url = "https://janisdd.gallery.vsassets.io/_apis/public/gallery/publisher/janisdd/extension/vscode-edit-csv/0.11.7/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-edit-csv-0.11.7.zip";
      sha256 = "sha256-8buRNSxfKmf9+MZDvFOOyrbXtbIC7GbHPRCBVnAHXrA=";
    };
  };
  "mattn.vscode-lisp" = {
    pname = "mattn.vscode-lisp";
    version = "09f9077526364501763414f8dd3a6aeff9e69f0e";
    src = fetchgit {
      url = "https://github.com/mattn/vscode-lisp.git";
      rev = "09f9077526364501763414f8dd3a6aeff9e69f0e";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-bwDh84e9d6hhsI8Bh5/fqG4dzx6YdG9dLTXtE4MVEhM=";
    };
    date = "2022-01-06";
  };
}
