# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  "evilz.vscode-reveal" = {
    pname = "evilz.vscode-reveal";
    version = "4.3.3";
    src = fetchurl {
      url = "https://evilz.gallery.vsassets.io/_apis/public/gallery/publisher/evilz/extension/vscode-reveal/4.3.3/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-reveal-4.3.3.zip";
      sha256 = "sha256-KqvQi0DMfHppX96qKHIkO9zIueBdGGV+6dYkpFEzFBo=";
    };
  };
  "janisdd.vscode-edit-csv" = {
    pname = "janisdd.vscode-edit-csv";
    version = "0.11.7";
    src = fetchurl {
      url = "https://janisdd.gallery.vsassets.io/_apis/public/gallery/publisher/janisdd/extension/vscode-edit-csv/0.11.7/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-edit-csv-0.11.7.zip";
      sha256 = "sha256-8buRNSxfKmf9+MZDvFOOyrbXtbIC7GbHPRCBVnAHXrA=";
    };
  };
  "mattn.lisp" = {
    pname = "mattn.lisp";
    version = "0.1.12";
    src = fetchurl {
      url = "https://mattn.gallery.vsassets.io/_apis/public/gallery/publisher/mattn/extension/Lisp/0.1.12/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "Lisp-0.1.12.zip";
      sha256 = "sha256-x6aFrcX0YElEFEr0qA669/LPlab15npmXd5Q585pIEw=";
    };
  };
}
