["evilz.vscode-reveal"]
src.vsmarketplace   = "evilz.vscode-reveal"
fetch.vsmarketplace = "evilz.vscode-reveal"

["janisdd.vscode-edit-csv"]
src.vsmarketplace   = "janisdd.vscode-edit-csv"
fetch.vsmarketplace = "janisdd.vscode-edit-csv"

["mattn.lisp"]
src.vsmarketplace   = "mattn.Lisp"
fetch.vsmarketplace = "mattn.Lisp"
